baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ruoshen Mo'

[[menus.main]]
name = 'About'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Publications'
pageRef = '/publications'
weight = 2

[[menus.main]]
name = 'Teaching'
pageRef = '/teaching'
weight = 3

[[menus.main]]
name = 'Misc'
pageRef = '/misc'
weight = 4